### ISSUE TITLE
Proxy SSL Termination

### ISSUE THREAD

**Issue by scottjbaldwin** [mdschweda/AspNetCore.SslRedirect#2]
This library is exactly what we're looking for, but in our testing, we have come across a small problem. The library doesn't support proxy SSL Termination. Many Proxies such as HAProxy, AWS Elastic Load Balancer etc... allow for SSL termination, and as such, even though we know the endpoint is secure (to the outside world), the protocol between the proxy and the server is http, which of course won't pass the `Request.IsHttps` check.

There is a standard protocol for `X-Forwarded-` headers explained [here](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html) which can help. 

Would you mind if I raised a Pull Request to add this option to your library?

**Comment by mdschweda** [comment]
I took your code as a basis for a less opinionated approach. Version 1.0.4 introduces `SslRedirectOptions.Filter`

> #### SslRedirectOptions.Filter
> Gets or sets a delegate that wraps SSL redirection.
> 
> *This delegate can modify the `SslRedirectOptions` on a per-request basis and instruct the termination of SSL redirection.*

This delegate receives a `SslRedirectContext` object containing, among other, information about potential Forward headers information, including `X-Forwarded-*` and other non-standard headers, as well as [RFC 7239](https://tools.ietf.org/html/rfc7239) *Forwarded HTTP Extension* data.

**Comment by scottjbaldwin** [comment]
That's great, when will this be pushed to nugget? I'm very keen to try it out.

**Comment by scottjbaldwin** [comment]
So correct me if I'm wrong... the usage is something like this?

```                    options.Filter = (c =>
                    {
                        return c.ForwardedHeader.Protocol != ProtocolType.Https;
                    });
```

**Comment by mdschweda** [comment]
Yes, this will make sure that SSL is not reestablished when the request contains a proto header. It seems that the load balancer can be short-circuited in your scenario. Since you can inspect the HttpContext more precautions can be made, e.g. check for known request sources.

**Comment by scottjbaldwin** [comment]
Thanks heaps for adding this.
